"""Add is_read to contacts

Revision ID: 7ea8e504bae3
Revises: 3cc3a0d288d9
Create Date: 2025-09-06 10:33:28.664037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea8e504bae3'
down_revision = '3cc3a0d288d9'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        
        # Заполняем старые записи значением False
    op.execute("UPDATE contacts SET is_read = FALSE WHERE is_read IS NULL")
    
     # Теперь запрещаем NULL
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('is_read', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
